### ISSUE TITLE
Launch task "attach android" fails

### ISSUE THREAD

**Issue by j3k0** [BowlerHatLLC/vscode-swf-debug#33]
I get an error when trying to execute the following launch task:

```json
{
  "type": "swf",
  "request": "attach",
  "applicationID": "my.app.id",
  "name": "Attach SWF (Android)",
  "platform": "android",
  "profile": "mobileDevice",
  "connect": true,
  "preLaunchTask": "Adobe AIR: package Android debug - asconfig-mobile.json"
}
```

<img width="454" alt="Screen Shot 2021-10-19 at 09 55 24" src="https://user-images.githubusercontent.com/191881/137858902-bb302c61-efb4-487d-b788-4daad29f787f.png">

I've tried many different things but can't figure out where the problem comes from.

Any way I can access some logs?

**Comment by joshtynjala** [comment]
@j3k0 It is trying to automatically find your apk path, but it cannot because you seem to specify it in a file named _asconfig-mobile.json_ instead of _asconfig.json_. A future update to vscode-swf-debug will allow you to specify `"asconfigPath": "asconfig-mobile.json"`. However, this update has not been released yet.

In the meantime, you can manually specify the path to your apk using the "bundle" field in _launch.json_.

**Comment by j3k0** [comment]
Thanks. That did the trick!
